### ISSUE TITLE
Relationship attributes

### ISSUE THREAD

**Issue by grockit-mmol** [neoid-gem/neoid#16]
Sorry if this is covered somewhere but I could not find it.  Is there a way to define an atribute on relations?  created_at would be incredible useful for me and I can't figure out how to get it in there.

**Comment by elado** [comment]
Definitely, exactly like it's done on nodes:

``` ruby
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  include Neoid::Relationship

  neoidable do |c|
    c.relationship start_node: :user, end_node: :movie, type: :likes
    c.field :created_at { self.created_at.to_i }
  end
end
```

I converted it to int, as Neo4j doesn't have date type (AFAIK).

**Comment by grockit-mmol** [comment]
Great, thanks a lot.
