### ISSUE TITLE
Non-model backed relationships

### ISSUE THREAD

**Issue by grockit-mmol** [neoid-gem/neoid#17]
I am trying to create a relationship that is not backed by an active record relationship and wondered if this is supported in some way.  Specifically what I am trying to do is have a relationship between a user and the board they created

``` ruby
class Board < ActiveRecord::Base
  belongs_to :user

  include Neoid::Node
  neoidable do |c|
    c.field :title
    c.field :created_at
  end

  include Neoid::Relationship
  neoidable do |c|
    c.relationship start_node: :user, end_node: :board, type: :created_board
    c.field :created_at
  end

  def board
    self
  end
end

class User < ActiveRecord::Base
  has_many :boards
end
```

It doesn't error out, but it also just hangs when I try and backfill data with neo_save

**Comment by elado** [comment]
As for now, `belongs_to` relationships are not supported, but a PR is welcome.

**Comment by BenMorganIO** [comment]
No. This is functionality Neoid will never have. Please see the [Neo4j gem](https://github.com/andreasronge/neo4j/) and my [blog post](http://blog.benmorgan.io/post/88913410501/getting-started-with-neo4j-ruby-2-1-2-and-rails-4-1-1) on implementing it.
