### ISSUE TITLE
Example of a self referential relationship 

### ISSUE THREAD

**Issue by matthewford** [neoid-gem/neoid#2]
Hi, 

I was wondering what would be the best way to define a self referential relationship neoid, for example:

```
class User
  has_many :follows
  has_many :followed_users, through: :follows
end

class Follow < ActiveRecord::Base
  belongs_to :user  
  belongs_to :followed_user, :class_name => 'User'  
end
```

**Comment by matthewford** [comment]
I'm putting this down to 2:50am coding, because:

```
  neoidable start_node: :user, end_node: :followed_user, type: :follows
```

Works just fine. Not sure what I was seeing before (probably put user,user).

**Comment by elado** [comment]
Glad you've found it working. Keep up the feedbacks.
