### ISSUE TITLE
Neoid with Neo4j 2.0.0-RC1 Gremlin Plugin Missing

### ISSUE THREAD

**Issue by sebastianwoinar** [neoid-gem/neoid#29]
With Neo4j version 2 the Gremlin Plugin isn't installed initially anmore.
See: https://groups.google.com/forum/#!searchin/neo4j/gremlinplugin/neo4j/aaxly1mH2Q4/MKJqjtTu2nwJ

Therefore, we have to add it manually. 
Could you add one or two line to the README.MD to reflect these changes. 
It would have saved me some time ;-)

Neography answers with 'No such ServerPlugin: "GremplinPlugin"'
when executing in neoid.rb:113
    value = Neoid.db.execute_script(gremlin_query, script_vars)

You can find it here:
https://github.com/neo4j-contrib/gremlin-plugin

**Comment by auxbuss** [comment]
What do you provide as the gremlin_path to neography, in this case?

I've tried various values in:

```
Neography.configure do |config|
  config.gremlin_path       = "/ext/GremlinPlugin/graphdb/execute_script"
end
```

but nothing I have tried works. The result is neography crashing when neoid tries to initialize Gemlin.

neo4j returns that gremlin is available:

```
HTTP :GET /db/data/ext

{
  "GremlinPlugin": "http://localhost:7474/db/data/ext/GremlinPlugin"
}
```

**Comment by istvanp** [comment]
I am having the same issue as well (neo4j 2.0.1).

**Comment by BenMorganIO** [comment]
Same here. @elado may be able to provide with some help on this :)

**Comment by BenMorganIO** [comment]
Considering I'm now the owner, I'll have to fix this. Running the tests on Neo4j 2.1.1 and straight Fs. If anyone wants to help out, much appreciated.

**Comment by BenMorganIO** [comment]
Closing this since Issue #39 has been created. All discussion should be moved there.
