### ISSUE TITLE
Delete relationship issue

### ISSUE THREAD

**Issue by sawilde** [neoid-gem/neoid#3]
I am experimenting with neo4j 1.6 using neoid.

I have created a simple User (node) + Follows (relationship) model (I mean who doesn't :))

When I create a relationship between two User entities I see the relationship appear in neo4j and in my RBDMS (postgresql), however when I delete that relationship I am not seeing the relationship be removed in neo4j even though it has been removed from the RBDMS. 

I checked the ActiveRecord after_destroy callback tree and I can see the neo_destroy method is there.

I am updating my relationships using the following 

```
user.friends = (user.friends - old_ids)        
user.friends = (user.friends + new_ids)         
user.save
```

so I am not calling .destroy directly but would assume it was implicit

**Comment by sawilde** [comment]
It would appear that the callback _after_destroy_ **is not** being called when

```
user.friends = (user.friends - old_ids)        
```

I am not sure why this is the behaviour because _after_create_ **is** being when 

```
user.friends = (user.friends + new_ids) 
```

I'd assume that when a relationship record is deleted then the _after_destroy_ would be called - but this does not appear to be the case, instead I have to use .destroy_all 

Perhaps you can tell me why this is?

**Comment by sawilde** [comment]
Talking to those in the know this 'lack' if calling after_destroy when an object is deleted from tgevdb like this 'is' expected. Another bit of rails/ruby lore to add to the collection.

**Comment by elado** [comment]
Yeah. By Rails' design, unfortunately. I definitely disagree with it...

**Comment by elado** [comment]
Gonna commit a fix.
