### ISSUE TITLE
Question about the generated graph

### ISSUE THREAD

**Issue by matthewford** [neoid-gem/neoid#4]
Hi, I'm taking a look at my graph and i'm not sure if it's a neo4j issue, or a neoid, but I have multiple sub ref nodes (repos in this case).

```
neo4j-sh (0)$ ls
==> (me)-[:tags_subref]->(tags_subref,8)
==> (me)-[:users_subref]->(users_subref,6)
==> (me)-[:repos_subref]->(repos_subref,5)
==> (me)-[:repos_subref]->(repos_subref,4)
==> (me)-[:repos_subref]->(repos_subref,3)
==> (me)-[:bookmarks_subref]->(bookmarks_subref,1)
```

I can post a copy of my graph if it helps, or is this perfectly normal?

**Comment by sawilde** [comment]
Looks odd compared to mine - I would have thought you would only have one per Neoid::node type - have you tried clearing down your db and starting again?

**Comment by matthewford** [comment]
I will do, the heroku plugin is down atm, so I'll have to wait to reload my data, but I can try more tests on local. 

My next question is, is there a way to regen my graph from the current db, or do I need to drop everything?

**Comment by elado** [comment]
This is not a normal case. Does it happen with latest version?

You can delete all the graph with `Neoid.clean_db(:yes_i_am_sure)` and regenerate all nodes with

``` ruby
[ RelationshipModel1, RelationshipModel2 ].each { |model| model.all.each(&:neo_save) }
```

This will loop through all of your RelationshipModel records and generate the two edge nodes along with a relationship.
For large data sets use pagination.

**Update**: Use batches as described in the readme.
