### ISSUE TITLE
relationship properties not supported by neoid

### ISSUE THREAD

**Issue by allen13** [neoid-gem/neoid#8]
After digging through the code I couldn't find any support for neo4j relationship properties. They are supported by the underlying [neography library](https://github.com/maxdemarzi/neography/blob/master/lib/neography/relationship.rb) . Was there a reason this feature was left out?

**Comment by oli-g** [comment]
I made a [pull request](https://github.com/elado/neoid/pull/10) for this.

**Comment by elado** [comment]
Recent commits solved that. Thanks for reporting!
