### ISSUE TITLE
database.yml

### ISSUE THREAD

**Issue by nakamorichi** [neoid-gem/neoid#9]
What kind of database.yml file should I have for neoid? Neoid uses ActiveRecord, and AR requires valid database.yml, but I couldn't find any info on how to configure it. I'm using only Neo4j in my app.

**Comment by elado** [comment]
Neoid works with AR and regular DB (like MySQL or SQLite). It mirrors the DB data to Neo4j so you can query Neo4j much faster than querying MySQL on 'graphy' data. And it uses normal database.yml as in every Rails app.

If you want to have only Neo4j, Neoid is not your solution. Try Neology instead.
